name: Build & Submit (Android; iOS manual)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g eas-cli
      - run: npm install
      - name: Write Google Play service account
        run: echo "${ANDROID_SERVICE_ACCOUNT_JSON}" > play.json
        env:
          ANDROID_SERVICE_ACCOUNT_JSON: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
      - name: Build (Android, cloud)
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: Submit to Google Play (Internal track)
        run: eas submit -p android --latest --track internal --key play.json --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  ios:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} # actívalo manual cuando tengas llaves de Apple
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g eas-cli
      - run: npm install
      - name: Build (iOS, cloud)
        run: eas build --platform ios --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - name: Submit to App Store Connect
        run: eas submit -p ios --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
